### ISSUE TITLE
Clear structure for koa.js app

### ISSUE THREAD

**Issue by hung-phan** [hung-phan/all-hail-the-R#3]
I find very interesting document saying how we should structure the application for node.js app based. Have a look.

`https://github.com/focusaurus/express_code_structure`

**Comment by nqbao** [comment]
@hung-phan your change on master on refactor the middlewares looks good. I think we can improve this part https://github.com/hung-phan/all-hail-the-R/blob/master/config/initializers/middlewares.js#L88

```
  applyMiddlewares(app, middlewares.bodyParser, settings.bodyParser);
  applyMiddlewares(app, middlewares.logger, settings.logger);
  applyMiddlewares(app, middlewares.compress, settings.compress);
  applyMiddlewares(app, middlewares.conditional, settings.conditional);
``` 

Should we use a for here? Given that the order of the middleware matters a lot, maybe we should change the middleware settings to an array of object.

**Comment by hung-phan** [comment]
:+1: make sense. Let me do it
